version: '3.3.1'
services:
  web:
    # image: pongsaphakmw/ruby-registration-form:latest
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./db:/app/db
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}